task: detection

num_classes: 4
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /root/autodl-tmp/dataset/road/images/train/
    ann_file: /root/autodl-tmp/dataset/road/annotations/train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 4
  num_workers: 0
  drop_last: True


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /root/autodl-tmp/dataset/road/images/val/
    ann_file: /root/autodl-tmp/dataset/road/annotations/val.json
    transforms:
      type: Compose
      ops: ~

  shuffle: False
  batch_size: 4
  num_workers: 0
  drop_last: False